### ISSUE TITLE
Problem with the images

### ISSUE THREAD

**Issue by 13tem** [kallerosenbaum/grokkingbitcoin#2] opened 2019-09-19 10:40 UTC
Images aren't being shown. Can't view any of them while reading though the chapters.

**Comment by kallerosenbaum** [comment] 2019-09-22 18:57
This is known, and not actually an issue, since it's by design. The content is not currently readable directly on GitHub. If you want to view the content, go to http://rosenbaum.se/book where I serve the generated book content.

The reason for it not being readable on github is that the images are in .eps format in git. To make the required .svg images the book has to be built using `make` on a linux machine (see https://github.com/kallerosenbaum/grokkingbitcoin/blob/master/readme.md). Eps is used because that's the actual source format that Manning uses. I *think* we need to keep the .eps files out of (at least) printing reasons. If we one day make a 2nd edition, we will need .eps.

I'm closing this for now, but I do agree that it'd be neat to browse the content directly on GitHub.

**Closed by kallerosenbaum** 2019-09-22 18:57 UTC
